# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('release_date', models.DateField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_explain', models.CharField(max_length=50)),
                ('product_classify', models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')], help_text='产品类别')),
                ('release_status', models.BooleanField(choices=[(False, '未发版'), (True, '发版')], default=False)),
                ('release_number', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '版本产品',
                'verbose_name_plural': '版本产品',
            },
        ),
        migrations.CreateModel(
            name='VersionRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('version_id', models.CharField(max_length=50)),
                ('release_status', models.BooleanField(choices=[(False, '未发版'), (True, '发版')], default=False)),
                ('release_number', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': '版本库表',
                'verbose_name_plural': '版本库表',
            },
        ),
        migrations.AddField(
            model_name='versionproduct',
            name='version_id',
            field=models.ForeignKey(help_text='版本号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_product', to='version_manage.VersionRepository'),
        ),
    ]
