# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0002_auto_20180920_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionproduct',
            name='product_version',
            field=models.CharField(default='', max_length=50),
        ),
    ]
