# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0004_auto_20180925_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
    ]
