# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0005_auto_20180925_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionrepository',
            name='release_number',
            field=models.CharField(default='', max_length=5),
        ),
    ]
