# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0006_auto_20180926_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='product_explain',
            field=models.TextField(),
        ),
    ]
