# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manage', '0007_auto_20180927_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='release_date',
            field=models.DateField(),
        ),
    ]
