# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 20:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder_manage', '0010_auto_20180413_2015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20180413_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(blank=True, null=True, verbose_name='购买数量')),
                ('m_order_goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_orders_goods', to='goods.MultipleGoods', verbose_name='订单中组合商品')),
            ],
            options={
                'verbose_name': '订单产品',
                'verbose_name_plural': '订单产品',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('order_year', models.IntegerField(default=1, verbose_name='购买年限')),
                ('give_day', models.IntegerField(default=0, verbose_name='赠送天数')),
                ('order_statu', models.IntegerField(choices=[('Financial_Control', '财务审核'), ('OPEN_SITE', '开站中'), ('Implement', '实施中'), ('Trade_Successfully', '交易完成'), ('FAILURE', '已失效')], default=1, verbose_name='订单状态')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('order_discount', models.IntegerField(default=100, verbose_name='折扣')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('open_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_info', to='workorder_manage.OpenStationManage')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_of', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField(choices=[('Financial_Control', '财务审核'), ('OPEN_SITE', '开站中'), ('Implement', '实施中'), ('Trade_Successfully', '交易完成'), ('FAILURE', '已失效')], verbose_name='订单状态')),
                ('order_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('order_operator', models.CharField(max_length=32, verbose_name='操作人')),
                ('responsible_person', models.CharField(max_length=32, verbose_name='经办人')),
                ('order_snz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_zt', to='order_manage.OrderInfo', verbose_name='订单交易')),
            ],
            options={
                'verbose_name': '订单状态',
                'verbose_name_plural': '订单状态',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.IntegerField(default=1, verbose_name='商品数量')),
                ('goods', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cat', to='goods.SingleGoods', verbose_name='已加入购物车单品')),
                ('m_goods', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cat', to='goods.MultipleGoods', verbose_name='已加入购物车的行业解决方案')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'trades_shoppingcat',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cp', to='order_manage.OrderInfo', verbose_name='订单信息'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='s_order_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_orders_goods', to='goods.SingleGoods', verbose_name='订单中单品'),
        ),
    ]
