# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'permissions': (('view_ordergoods', 'Can see available order goods'),), 'verbose_name': '订单产品', 'verbose_name_plural': '订单产品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'permissions': (('view_orderinfo', 'Can see available order info'),), 'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'permissions': (('view_orderstatus', 'Can see available order status'),), 'verbose_name': '订单状态', 'verbose_name_plural': '订单状态'},
        ),
    ]
