# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=24, null=True, verbose_name='版本号')),
                ('down_address', models.TextField(null=True, verbose_name='下载地址')),
                ('classify', models.SmallIntegerField(blank=True, choices=[(2, '重构版'), (1, '经典版')], null=True, verbose_name='版本类型')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='新增时间')),
            ],
            options={
                'verbose_name': '客户端下载模块',
                'verbose_name_plural': '客户端下载模块',
            },
        ),
    ]
