# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0018_auto_20180413_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='grid',
            name='getFlashserver',
            field=models.TextField(default='', verbose_name='服务端'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='versionInfos',
            field=models.ManyToManyField(db_constraint=False, default='', related_name='grid', to='production_manage.VersionInfo'),
        ),
    ]
