# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0019_auto_20180511_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='visitors',
            field=models.TextField(default='', verbose_name='访客端'),
        ),
    ]
