# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0020_grid_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsyAliCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('grid_name', models.CharField(max_length=100, verbose_name='服务器实例名称')),
                ('date', models.DateField(verbose_name='记录时间')),
                ('cloud', models.SmallIntegerField(choices=[(0, '金山云'), (1, '阿里云')], verbose_name='云分类')),
                ('sum', models.CharField(max_length=100, verbose_name='时间段流量总和')),
                ('allocation_id', models.CharField(max_length=100, verbose_name='eip实例id')),
            ],
            options={
                'verbose_name': '服务器流量统计表',
                'verbose_name_plural': '服务器流量统计表',
            },
        ),
    ]
