# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_manage', '0021_ksyalicloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grid',
            name='is_enable',
        ),
    ]
