# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0006_auto_20171013_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (4, '登录'), (5, '退出'), (500, '其他'), (6, '浏览')], null=True),
        ),
    ]
