# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0007_auto_20180719_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, null=True, verbose_name='字段')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='名称')),
                ('new_value', models.CharField(max_length=128, null=True, verbose_name='新值')),
                ('old_value', models.CharField(max_length=128, null=True, verbose_name='旧值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log_manage.OperateLog')),
            ],
            options={
                'verbose_name': '日志详情模块',
                'verbose_name_plural': '日志详情模块',
            },
        ),
    ]
