# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0008_detaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillog',
            name='log_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oper_of', to='log_manage.OperateLog'),
        ),
    ]
