# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180413_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'permissions': (('view_advertising', 'Can see available advertising'),), 'verbose_name': '广告管理', 'verbose_name_plural': '广告管理'},
        ),
        migrations.AlterModelOptions(
            name='goodsmodel',
            options={'permissions': (('view_goodsmodel', 'Can see available goods model'),), 'verbose_name': '商品模块配置', 'verbose_name_plural': '商品模块配置'},
        ),
        migrations.AlterModelOptions(
            name='multiplegoods',
            options={'permissions': (('view_multiplegoods', 'Can see available multiplegoods'),), 'verbose_name': '组合商品管理', 'verbose_name_plural': '组合商品管理'},
        ),
        migrations.AlterModelOptions(
            name='putaway',
            options={'permissions': (('view_putaway', 'Can see available putaway'),), 'verbose_name': '商品上架信息', 'verbose_name_plural': '商品上架信息'},
        ),
        migrations.AlterModelOptions(
            name='singlegoods',
            options={'permissions': (('view_singlegoods', 'Can see available singlegoods'),), 'verbose_name': '单品管理', 'verbose_name_plural': '单品管理'},
        ),
        migrations.AlterModelOptions(
            name='tagclass',
            options={'permissions': (('view_tagclass', 'Can see available tagclass'),), 'verbose_name': '标签模块配置', 'verbose_name_plural': '标签模块配置'},
        ),
    ]
