# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180426_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, help_text='是否可用')),
                ('param_options_name', models.CharField(default='Ture', max_length=100, verbose_name='控件选项名称')),
                ('param_options_value', models.CharField(default='Ture', max_length=100, verbose_name='控件选项值')),
            ],
            options={
                'verbose_name': '产品规格和参数选项',
                'verbose_name_plural': '产品规格和参数选项',
            },
        ),
        migrations.CreateModel(
            name='SpecificationParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, help_text='是否可用')),
                ('file_name', models.CharField(max_length=25, verbose_name='字段名称')),
                ('fill_control', models.IntegerField(choices=[(0, '单行文本框'), (1, '下拉列表框')], default=1, verbose_name='填写控件类型')),
                ('param_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_model', to='goods.GoodsModel', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '产品规格和参数',
                'verbose_name_plural': '产品规格和参数',
            },
        ),
        migrations.RemoveField(
            model_name='putaway',
            name='m_up_goods',
        ),
        migrations.RemoveField(
            model_name='putaway',
            name='s_up_goods',
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='put_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='上架价格', max_digits=11, verbose_name='组合上架价格'),
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='putaway_off_time',
            field=models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='putaway_operator',
            field=models.CharField(blank=True, default='putaway_operator', help_text='操作人', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='putaway_recent_on_time',
            field=models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='上架时间'),
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='recommend',
            field=models.SmallIntegerField(choices=[(1, '展示'), (2, '不展示')], default=2, verbose_name='是否首页展示'),
        ),
        migrations.AddField(
            model_name='multiplegoods',
            name='sell_status',
            field=models.SmallIntegerField(choices=[(1, '预售'), (2, '可售卖')], default=1, help_text='售卖状态', verbose_name='售卖状态'),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='put_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='上架价格'),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='putaway_off_time',
            field=models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='putaway_operator',
            field=models.CharField(blank=True, default='putaway_operator', help_text='操作人', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='putaway_recent_on_time',
            field=models.DateField(blank=True, default='1970-01-01', null=True, verbose_name='上架时间'),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='recommend',
            field=models.SmallIntegerField(choices=[(1, '展示'), (2, '不展示')], default=2, verbose_name='是否首页展示'),
        ),
        migrations.AddField(
            model_name='singlegoods',
            name='sell_status',
            field=models.SmallIntegerField(choices=[(1, '预售'), (2, '可售卖')], default=1, help_text='售卖状态', verbose_name='售卖状态'),
        ),
        migrations.AlterField(
            model_name='tagclass',
            name='goods_tag',
            field=models.CharField(max_length=16, verbose_name='商品标签'),
        ),
        migrations.AlterUniqueTogether(
            name='tagclass',
            unique_together=set([('label_category', 'goods_tag')]),
        ),
        migrations.DeleteModel(
            name='Putaway',
        ),
        migrations.AddField(
            model_name='parameteroptions',
            name='control',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_control', to='goods.SpecificationParameter', verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='parameteroptions',
            name='multiple_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_par_options', to='goods.MultipleGoods', verbose_name='行业解决方案'),
        ),
        migrations.AddField(
            model_name='parameteroptions',
            name='single_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='par_options', to='goods.SingleGoods', verbose_name='单价产品'),
        ),
    ]
