# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180725_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='detailimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='introduceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='introduceimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='multiplegoods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='multiplegoods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='singlegoods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='singlegoods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='successcaseimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='successcaseimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
    ]
