# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0009_stationinfo_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinfo',
            name='cli_version',
            field=models.IntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')]),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='company_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='deploy_way',
            field=models.IntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版'), (5, '公有云')]),
        ),
    ]
