# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0010_auto_20180413_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='order_work',
            field=models.CharField(default='页面创建', max_length=18, verbose_name='开站标识'),
        ),
    ]
