# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_remove_sitereceptiongroup_site'),
        ('workorder_manage', '0011_stationinfo_order_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='set_up',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_info', to='setup.SiteReceptionGroup'),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='deploy_way',
            field=models.IntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云')]),
        ),
    ]
