# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0012_auto_20180511_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='amount_cashed',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='回款金额'),
        ),
        migrations.AddField(
            model_name='stationinfo',
            name='contract_amount',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='合同金额'),
        ),
    ]
