# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0014_auto_20180703_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='version_id',
            field=models.SmallIntegerField(choices=[(1, 'grid'), (2, 'grid1')], default=1, verbose_name='版本ID'),
        ),
    ]
