# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0015_stationinfo_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinfo',
            name='deploy_way',
            field=models.IntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')]),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='version_id',
            field=models.SmallIntegerField(choices=[(1, 'grid'), (2, 'grid1'), (3, 'grid2'), (4, 'grid3'), (5, 'grid4')], default=1, verbose_name='版本ID'),
        ),
    ]
