# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0016_auto_20180830_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='openstationmanage',
            name='its_parent',
            field=models.ForeignKey(default='', max_length=18, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='workorder_manage.OpenStationManage', verbose_name='子站的父类id'),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='classify',
            field=models.SmallIntegerField(choices=[(2, '重构版'), (1, '经典版')], help_text='产品类别', null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='cli_version',
            field=models.IntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')], null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='deploy_way',
            field=models.IntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='impl_cslt',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='oper_cslt',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='oper_supt',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='pre_sales',
            field=models.CharField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='sales',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
