# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0017_auto_20180928_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyurl',
            name='company_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
