# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0018_auto_20181011_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start_time', models.DateField(default='', verbose_name='合同开始时间')),
                ('contract_end_time', models.DateField(default='', verbose_name='合同结束时间')),
                ('contract_index', models.CharField(blank=True, max_length=30, null=True, verbose_name='合同编号')),
                ('contract_accessory', models.TextField(blank=True, null=True, verbose_name='附件')),
                ('contract_amount', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='合同金额')),
                ('amount_cashed', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='回款金额')),
                ('cashed_time', models.DateField(default='', verbose_name='回款时间')),
                ('create_time', models.DateField(default='', verbose_name='创建时间')),
                ('contract_content', models.TextField(blank=True, max_length=30, null=True, verbose_name='合同编号')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.RemoveField(
            model_name='stationinfo',
            name='amount_cashed',
        ),
        migrations.RemoveField(
            model_name='stationinfo',
            name='contract_amount',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='brand_effect',
            field=models.IntegerField(choices=[(1, '世界500强'), (2, '中国500强'), (3, '行业前10'), (0, '无')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='consult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='customer_level',
            field=models.IntegerField(choices=[(0, '无'), (1, 'A'), (2, 'B'), (3, 'C')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='kf_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='platform_informatiom',
            field=models.TextField(blank=True, null=True, verbose_name='平台信息'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sign_contract',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='special_selection',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='training_method',
            field=models.IntegerField(choices=[(0, '无'), (1, '远程'), (2, '现场'), (3, '远程+现场')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='transmitting_state',
            field=models.IntegerField(choices=[(0, '无'), (1, '待审批'), (2, '审批通过'), (3, '审批驳回')], default=0),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='visitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='link_type',
            field=models.IntegerField(choices=[(1, '客户方业务'), (2, '客户方项目'), (3, '客户方技术'), (4, '商务（小能）')], default=1),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='link_work',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='link_qq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkman',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='order_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to='workorder_manage.OrderManage'),
        ),
    ]
