# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0020_auto_20181015_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='驳回理由'),
        ),
    ]
