# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0021_auto_20181015_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='company',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_info', to='workorder_manage.CompanyInfo'),
        ),
    ]
