# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0022_contactinfo_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermanage',
            name='create_time',
        ),
        migrations.AddField(
            model_name='ordermanage',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
