# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0023_auto_20181016_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='transmitting_state',
            field=models.IntegerField(choices=[(0, '审批通过'), (1, '待审批'), (2, '审批驳回')], default=1),
        ),
    ]
