# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0024_auto_20181016_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='classify',
            field=models.SmallIntegerField(blank=True, choices=[(2, '重构版'), (1, '经典版')], null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='deploy_way',
            field=models.IntegerField(blank=True, choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], null=True),
        ),
    ]
