# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0026_auto_20181018_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanage',
            name='contract_content',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='合同内容'),
        ),
    ]
