# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0028_auto_20181019_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermanage',
            name='cashed_time',
        ),
        migrations.AddField(
            model_name='ordermanage',
            name='cashed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='回款时间'),
        ),
    ]
