# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0029_auto_20181022_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermanage',
            old_name='cashed_at',
            new_name='cashed_time',
        ),
    ]
