# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-31 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder_manage', '0030_auto_20181022_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkEvolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('mark_type', models.IntegerField(blank=True, choices=[(1, '备注'), (2, '最新进展'), (3, '客户需求沟通结果')], null=True, verbose_name='备注类型')),
                ('company', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_of', to='workorder_manage.CompanyInfo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '客户库备注',
                'verbose_name_plural': '客户库备注',
            },
        ),
    ]
