# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0031_remarkevolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarkevolve',
            name='mark_type',
            field=models.IntegerField(blank=True, choices=[(1, '备注'), (3, '客户需求沟通结果')], null=True, verbose_name='备注类型'),
        ),
    ]
