# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder_manage', '0032_auto_20181101_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('enclosure', models.TextField(null=True, verbose_name='附件')),
                ('step_atta', models.CharField(max_length=64, null=True, verbose_name='操作步骤')),
            ],
            options={
                'verbose_name': '培训问题上传的附件',
                'verbose_name_plural': '培训问题上传的附件',
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('matter_type', models.SmallIntegerField(blank=True, choices=[(1, '培训')], null=True, verbose_name='问题类型')),
                ('matter_status', models.SmallIntegerField(blank=True, choices=[(1, '培训信息提交'), (2, '讲师分配完成'), (3, '驳回'), (4, '培训需求确认完成'), (5, '培训准备完成'), (6, '培训挂起'), (7, '终止培训'), (8, '培训完成'), (9, '交接完成'), (10, '遗留问题已确认'), (11, '调查人员已分配'), (12, '培训任务完成')], null=True, verbose_name='问题状态')),
                ('training_method', models.SmallIntegerField(blank=True, choices=[(0, '无'), (1, '远程'), (2, '现场')], null=True, verbose_name='培训方式')),
                ('legacy_issue', models.SmallIntegerField(blank=True, choices=[(1, '有遗留问题'), (0, '没有遗留问题')], null=True, verbose_name='是否有遗留问题')),
                ('satisfaction_level', models.SmallIntegerField(blank=True, choices=[(5, '非常满意'), (4, '满意'), (3, '一般'), (2, '不满意'), (1, '非常不满意')], null=True, verbose_name='满意度等级')),
                ('final_training_method', models.SmallIntegerField(blank=True, choices=[(0, '无'), (1, '远程'), (2, '现场')], null=True, verbose_name='最终培训方式')),
                ('matter_name', models.CharField(max_length=64, null=True, verbose_name='问题名称')),
                ('training_contact', models.CharField(max_length=16, null=True, verbose_name='培训联系人职位')),
                ('training_contactnum', models.CharField(max_length=16, null=True, verbose_name='培训联系人电话')),
                ('training_contactqq', models.CharField(max_length=16, null=True, verbose_name='培训人QQ')),
                ('training_position', models.CharField(max_length=16, null=True, verbose_name='培训联系人职位')),
                ('invest_start', models.DateTimeField(null=True, verbose_name='调查开始时间')),
                ('invest_end', models.DateTimeField(null=True, verbose_name='调查结束时间')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('description_customer', models.TextField(null=True, verbose_name='客户现状描述')),
                ('online_module', models.TextField(null=True, verbose_name='已上线模块')),
                ('unonline_module', models.TextField(null=True, verbose_name='未上线模块')),
                ('communication_way', models.TextField(null=True, verbose_name='沟通方式')),
                ('untrained_cause', models.TextField(null=True, verbose_name='未培训原因')),
                ('termination_reason', models.TextField(null=True, verbose_name='终止原因')),
                ('customer_training_needs', models.TextField(null=True, verbose_name='客户培训需求')),
                ('training_model', models.TextField(null=True, verbose_name='培训模块')),
                ('problem_description', models.TextField(null=True, verbose_name='问题描述')),
                ('customer_feedback', models.TextField(max_length='客户反馈详情', null=True)),
                ('company_matter', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of_matter', to='workorder_manage.CompanyInfo')),
                ('dealing_person', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealing', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('investigador', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigate', to=settings.AUTH_USER_MODEL, verbose_name='调查人员')),
                ('responsible', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_user', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('training_instructors', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL, verbose_name='培训讲师')),
            ],
            options={
                'verbose_name': '培训相关问题',
                'verbose_name_plural': '培训相关问题',
            },
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('dismiss_reason', models.TextField(null=True, verbose_name='驳回理由')),
                ('matter_reject', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of_matter', to='workorder_manage.Matter')),
            ],
            options={
                'verbose_name': '培训问题驳回理由',
                'verbose_name_plural': '培训问题驳回理由',
            },
        ),
        migrations.AlterField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AlterField(
            model_name='openstationmanage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='openstationmanage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='atta_matter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matter_ofatta', to='workorder_manage.Matter'),
        ),
        migrations.AddField(
            model_name='remarkevolve',
            name='matter',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matter_mark', to='workorder_manage.Matter'),
        ),
    ]
