# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-18 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder_manage', '0034_auto_20181130_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('children_station', models.CharField(max_length=20, null=True, verbose_name='子站点')),
                ('open_id', models.CharField(max_length=16, verbose_name='开站id')),
                ('workorder_theme', models.CharField(max_length=50, null=True, verbose_name='工单主题')),
                ('subordinatemodule', models.CharField(max_length=128, null=True, verbose_name='所属模块')),
                ('func_name', models.CharField(max_length=128, null=True, verbose_name='功能名称')),
                ('func_value', models.TextField(null=True, verbose_name='功能选项值')),
                ('describe', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('allocation_people', models.CharField(max_length=16, null=True, verbose_name='分配人')),
                ('product_stautus', models.SmallIntegerField(blank=True, choices=[(3, '任务审核中'), (4, '云平台操作中'), (5, '云平台操作完成'), (6, '运维操作中'), (7, '运维操作完成'), (8, '操作方验证中'), (9, '需求方验证中'), (10, '验证通过'), (11, '任务关闭'), (12, '已驳回')], null=True, verbose_name='产品配置状态')),
                ('khk_id', models.CharField(max_length=8, verbose_name='客户库id')),
                ('allocate_time', models.DateTimeField(null=True, verbose_name='分配时间')),
                ('actual_start_time', models.DateTimeField(null=True, verbose_name='实际开始时间')),
                ('actual_completion_time', models.DateTimeField(null=True, verbose_name='实际完成时间')),
                ('dealing_person', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_dealing', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '产品配置',
                'verbose_name_plural': '产品配置',
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='atta_matter',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='matter_reject',
        ),
        migrations.RemoveField(
            model_name='remarkevolve',
            name='company',
        ),
        migrations.RemoveField(
            model_name='remarkevolve',
            name='matter',
        ),
        migrations.AddField(
            model_name='attachment',
            name='atta_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '培训管理'), (2, '产品配置')], null=True, verbose_name='附件类型'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='correlation_id',
            field=models.CharField(default=99, max_length=8, verbose_name='关联id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reject',
            name='correlation_id',
            field=models.CharField(default=10, max_length=8, verbose_name='关联id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reject',
            name='reject_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '培训管理'), (2, '产品配置'), (3, '操作方不通过原因'), (4, '需求方不通过原因')], null=True, verbose_name='驳回理由类型'),
        ),
        migrations.AddField(
            model_name='remarkevolve',
            name='correlation_id',
            field=models.CharField(default=1, max_length=8, verbose_name='关联id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='transmitting_state',
            field=models.IntegerField(choices=[(0, '审批通过'), (1, '待审批'), (2, '审批驳回'), (3, '上线')], default=1),
        ),
        migrations.AlterField(
            model_name='remarkevolve',
            name='mark_type',
            field=models.IntegerField(blank=True, choices=[(1, '客户库备注'), (2, '问题备注'), (3, '客户需求沟通结果'), (4, '产品配置备注')], null=True, verbose_name='备注类型'),
        ),
        migrations.AlterField(
            model_name='stationinfo',
            name='company_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
