# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20171214_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='avatar',
            field=models.URLField(blank=True, default='', help_text='显示头像', null=True),
        ),
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='desc',
            field=models.CharField(blank=True, help_text='一句话介绍', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='manager',
            field=models.CharField(blank=True, help_text='接待经理', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='phone_number',
            field=models.CharField(blank=True, help_text='电话', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitereceptiongroup',
            name='url',
            field=models.URLField(blank=True, help_text='网址', null=True),
        ),
    ]
