# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_remove_sitereceptiongroup_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLdapConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_ldap_bind_dn', models.CharField(max_length=64)),
                ('auth_ldap_bind_password', models.CharField(max_length=32)),
                ('user_ldapsearch', models.CharField(max_length=64)),
                ('user_scope_subtree', models.CharField(max_length=24)),
                ('group_ldapsearch', models.CharField(max_length=64)),
                ('group_scope_subtree', models.CharField(max_length=128)),
                ('is_active', models.CharField(max_length=128)),
                ('is_staff', models.CharField(max_length=128)),
                ('is_superuser', models.CharField(max_length=128)),
                ('ldap_server_url', models.CharField(max_length=64)),
                ('login_model', models.SmallIntegerField(choices=[(1, 'LDAP登录模式'), (2, '本地登录模式'), (3, '本地+LDAP模式')], default=2)),
                ('ldap_name', models.CharField(max_length=128)),
                ('ldap', models.CharField(default='ldap', max_length=8)),
            ],
            options={
                'verbose_name': '登录模式配置',
                'verbose_name_plural': '登录模式配置',
                'permissions': (('view_loginconfig', 'Can see available loginconfig'),),
            },
        ),
    ]
