# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder_manage', '0008_auto_20171214_2100'),
        ('data_manage', '0008_auto_20171214_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiriesdata',
            name='open_id',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_data', to='workorder_manage.OpenStationManage'),
        ),
    ]
