# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0008_auto_20171214_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiriesdata',
            options={'permissions': (('view_pandect', '查看总览'), ('view_channel-inquiries', '查看线上渠道情况'), ('view_customer-use', '查看客户使用情况'), ('view_grid-inquiries', '查看节点情况'), ('view_sergrp-inquiries', '查看服务组情况')), 'verbose_name': '渠道别咨询量记录', 'verbose_name_plural': '渠道别咨询量记录'},
        ),
        migrations.AlterModelOptions(
            name='onlineclientdata',
            options={'permissions': (('view_online-client', '查看线上站点情况'),), 'verbose_name': '在线客户数量', 'verbose_name_plural': '在线客户数量'},
        ),
        migrations.AlterModelOptions(
            name='onlineproductdata',
            options={'permissions': (('view_online-product', '查看线上产品情况'),), 'verbose_name': '在线产品使用数量', 'verbose_name_plural': '在线产品使用数量'},
        ),
        migrations.AlterModelOptions(
            name='operatingrecord',
            options={'permissions': (('view_site-oper', '查看站点运营情况'),), 'verbose_name': '运营记录', 'verbose_name_plural': '运营记录'},
        ),
    ]
