# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0009_inquiriesdata_open_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiriesdata',
            old_name='open_id',
            new_name='open',
        ),
    ]
