# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0010_auto_20180122_1111'),
        ('data_manage', '0009_auto_20180115_1618'),
    ]

    operations = [
    ]
