# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0011_merge_20180124_1050'),
        ('data_manage', '0011_merge_20180125_1704'),
    ]

    operations = [
    ]
