# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0012_merge_20180130_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiriesdata',
            name='cli_version',
            field=models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')], help_text='客户版本'),
        ),
        migrations.AlterField(
            model_name='inquiriesdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版'), (5, '公有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineclientdata',
            name='cli_version',
            field=models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')], help_text='客户版本'),
        ),
        migrations.AlterField(
            model_name='onlineclientdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版'), (5, '公有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineproductdata',
            name='cli_version',
            field=models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')], help_text='客户版本'),
        ),
        migrations.AlterField(
            model_name='onlineproductdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版'), (5, '公有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='cli_version',
            field=models.SmallIntegerField(choices=[(1, 'B2B'), (2, 'B2C'), (3, '不限'), (4, 'B2B2C')], help_text='客户版本'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, 'VIP版'), (3, 'VPC版'), (4, '企业版'), (5, '公有云')], help_text='部署方式'),
        ),
    ]
