# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0013_auto_20180413_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiriesdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineclientdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineproductdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云')], help_text='部署方式'),
        ),
    ]
