# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0014_auto_20180511_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefactoringConsultingAndVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('date', models.DateField()),
                ('company_id', models.CharField(help_text='站点ID', max_length=50)),
                ('valid_consulting', models.IntegerField(default=0)),
                ('invalid_consulting', models.IntegerField(default=0)),
                ('valid_visitors', models.IntegerField(default=0)),
                ('invalid_visitors', models.IntegerField(default=0)),
                ('channel', models.SmallIntegerField(choices=[(6, 'PC'), (1, '微信'), (2, 'APP'), (3, 'WAP'), (4, 'IOS'), (5, 'Android'), (-1, '未知'), (7, '微博'), (8, 'QQ')], default=-1, help_text='渠道类别')),
                ('grid', models.CharField(help_text='节点', max_length=30)),
                ('industry', models.CharField(help_text='行业', max_length=30)),
                ('deploy', models.CharField(help_text='部署方式', max_length=30)),
            ],
            options={
                'verbose_name': '咨询量访客量重构版',
                'verbose_name_plural': '咨询量访客量重构版',
                'permissions': (('view_re_consulting_and_visitors', '查看咨询访客量'),),
            },
        ),
    ]
