# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0015_refactoringconsultingandvisitors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refactoringconsultingandvisitors',
            options={'permissions': (('view_re-consulting-and-visitors', '查看咨询访客量'),), 'verbose_name': '咨询量访客量重构版', 'verbose_name_plural': '咨询量访客量重构版'},
        ),
        migrations.AlterField(
            model_name='inquiriesdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineclientdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='onlineproductdata',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='operatingrecord',
            name='deploy_way',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], help_text='部署方式'),
        ),
        migrations.AlterField(
            model_name='refactoringconsultingandvisitors',
            name='channel',
            field=models.SmallIntegerField(choices=[(1, 'wechat'), (2, 'web'), (3, 'wap'), (4, 'IOS App'), (5, 'Android App'), (-1, '未知'), (7, 'weibo')], default=-1, help_text='渠道类别'),
        ),
        migrations.AlterField(
            model_name='refactoringconsultingandvisitors',
            name='deploy',
            field=models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], default=1, help_text='部署方式'),
        ),
    ]
