# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0016_auto_20180814_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='refactoringconsultingandvisitors',
            name='unique_vistor',
            field=models.IntegerField(default=0),
        ),
    ]
