# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0017_refactoringconsultingandvisitors_unique_vistor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='站点ID', max_length=50)),
                ('industry', models.CharField(help_text='所属行业', max_length=60)),
                ('deploy_way', models.SmallIntegerField(choices=[(1, '标准版'), (2, '公有云'), (3, '专属云'), (4, '私有云'), (5, '缺省')], help_text='部署方式')),
                ('grid', models.CharField(help_text='节点', max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='更新时间')),
                ('date', models.DateField(help_text='记录时间')),
                ('visitor_num', models.IntegerField(blank=True, default=0, help_text='访客数量', null=True)),
            ],
        ),
    ]
