# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manage', '0018_vistordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiriesdata',
            name='grid',
            field=models.CharField(default=0, help_text='节点', max_length=64),
            preserve_default=False,
        ),
    ]
